# Generated by Django 3.1.7 on 2021-04-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_products_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='availablility',
        ),
        migrations.AddField(
            model_name='products',
            name='availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
